[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_limit = 20000000
gas_reports = ["*"]

[rpc_endpoints]
filecoin-calibration = "https://calibration.filfox.info/rpc/v1"
filecoin-mainnet = "https://filfox.info/rpc/v1"

# Filecoin Calibration Configuration
[profile.calibration]
chain_id = 314159
eth_rpc_url = "https://calibration.filfox.info/rpc/v1"