name: Testnet Deployment Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  verify-deployment:
    name: Verify deployment script
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        run: |
          if [ ! -d "lib/forge-std" ] || [ -z "$(ls -A lib/forge-std)" ]; then
            rm -rf lib/forge-std
            git submodule add https://github.com/foundry-rs/forge-std lib/forge-std
          fi
          git submodule update --init --recursive

      - name: Copy env file
        run: cp .env.example .env

      - name: Verify deployment script compilation
        run: forge script script/Deploy.s.sol:DeployScript -vvv

  verify-contract-size:
    name: Contract size check
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check contract sizes
        run: forge build --sizes

  verify-storage-layout:
    name: Storage layout verification
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout Repository with Submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check storage layout
        run: forge inspect src/ParityWallet.sol:ParityWallet storage-layout
